ISPP-23-24-Grupo-3/musclemate-backend

equipment/serializers.py
equipment/urls.py
equipment/views.py

- Arreglado problema con el serializer del módulo Equipment tras extrar Assessments
- Añadido validador para comprobar que el gimnasio referido en la entidad exista
- Añadida vista para buscar Equipment por id
Closes #54

Arreglado error serializer y añadida vista detalle equipment #54

---

gym/serializers.py
ticket/serializers.py

Bug fix/63 actualizar serializer ticket

---

assessment/urls.py
assessment/views.py
equipment/urls.py

feat: creada vista assessment detail #81

---

workout/serializers.py

fix: cannot acces workout

---

client/tests.py
client/urls.py
gym/tests.py
reservation/tests.py

fix: arreglar test

---

client/serializers.py
client/views.py

fix: fallos del detail client

---

routine/urls.py
routine/views.py

feat: requisitos routine

---

assessment/urls.py
assessment/views.py

feat: requisitos assessment

---

event/tests.py

fix: arreglo de test y ampliación

---

client/tests.py
owner/tests.py
user/test.py
user/views.py

fix: arreglos de multiples test

---

.github/workflows/django.yml

Bug fix/152 migrations actions

---

routine/serializers.py
routine/urls.py
routine/views.py

fix: cambio de permisos listado rutinas

---

client/tests.py
client/views.py
equipment/tests.py
equipment/views.py
owner/tests.py

feat: test de equipment

---

ticket/tests.py
ticket/urls.py
ticket/views.py

feat: test de ticket

---

workout/tests.py
workout/urls.py
workout/views.py

fix: issue 180

---

client/views.py

fix: issue 181

---

ticket/views.py

bugfix: clientAuthority function to use username instead of user object

---

gym/urls.py
gym/views.py

Falta por implementar los test

feat:graficas maquinas #233

---

gym/views.py

Fallo en el filtro de las maquinas por gim, mostraba todas las maquinas de los gimnasios del owner, en lugar de mostrar unicamente las maquinas del gim.

fix:uso de las maquinas #256

---

equipment/views.py

…nd gym subscription validation

feature\264-restriccion-global

---

equipment/views.py

arreglado bug con estadisticas globales
Closes #273

fix: error con la vista de EquipmentGlobalList

---

event/urls.py
event/views.py

feat: vista para ver reservas
